### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kikkerslijm410**

### CODE REVIEW

**Comment by Kikkerslijm410** [comment]
i wil not take no for an answer YOU FRAUD

**Comment by Justwouter** [comment]
No my IQ is you to high to be insulted by such ignorance!

You can't defeat me I am a GOD how can you kill a god? Such a grand and intoxicating innocence.

**Comment by Kikkerslijm410** [comment]
yeah sounds like an idiot

**Comment by Justwouter** [comment]
For added effect : https://www.youtube.com/watch?v=1C8z2KAnP9A

**Pull request closed without merging**
